import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Baby, HeartPulse, ScanLine, Sparkles, Stethoscope, Syringe } from 'lucide-react';
import Reveal from '@/components/Reveal';
import { getArticles } from '@/lib/articles';
import { site, whatsapp } from '@/lib/site';

const focus=[
  {icon:ScanLine,title:'Cirurgia minimamente invasiva',text:'Laparoscopia e histeroscopia com indicação individualizada para diferentes condições ginecológicas.'},
  {icon:HeartPulse,title:'Saúde ginecológica',text:'Acompanhamento ao longo das diferentes fases da vida, com investigação e prevenção.'},
  {icon:Baby,title:'Obstetrícia',text:'Pré-natal de baixo e alto risco e acompanhamento do parto de forma respeitosa e humanizada.'}
];
const conditions=['Endometriose profunda','Miomas e pólipos','Adenomiose','Infertilidade','Sangramento uterino anormal','Menopausa','Incontinência urinária','Prolapsos genitais'];
export default async function Home(){const articles=(await getArticles()).slice(0,3);return <>
<section className="hero"><div className="hero-orb orb-a"/><div className="hero-orb orb-b"/><div className="container hero-grid">
  <div className="hero-copy"><Reveal><div className="eyebrow"><Sparkles size={15}/> Ginecologia · Obstetrícia · Maringá</div><h1>Saúde da mulher com <em>precisão e cuidado.</em></h1><p>Atendimento ginecológico e obstétrico com foco em cirurgia minimamente invasiva e acompanhamento individualizado.</p><div className="hero-actions"><a className="btn primary" href={whatsapp()} target="_blank">Agendar consulta <ArrowUpRight size={18}/></a><Link className="btn ghost" href="/sobre">Conhecer o Dr. Murillo</Link></div></Reveal></div>
  <Reveal delay={.14} className="hero-visual"><div className="image-frame"><Image src="/images/murillo-hero.webp" fill priority sizes="(max-width: 900px) 92vw, 42vw" alt="Dr. Murillo Santos, ginecologista em Maringá"/></div><div className="hero-caption"><span>Dr. Murillo Santos</span><small>Ginecologia e Obstetrícia</small></div></Reveal>
</div></section>
<section className="section"><div className="container"><Reveal><div className="section-head"><span className="kicker">Áreas de atuação</span><h2>Medicina moderna sem perder a proximidade.</h2><p>Da consulta preventiva ao tratamento cirúrgico, cada decisão começa com escuta, diagnóstico e indicação precisa.</p></div></Reveal><div className="focus-grid">{focus.map((x,i)=><Reveal key={x.title} delay={i*.08}><article className="focus-card"><x.icon/><span>0{i+1}</span><h3>{x.title}</h3><p>{x.text}</p><Link href="/tratamentos">Ver possibilidades <ArrowUpRight size={16}/></Link></article></Reveal>)}</div></div></section>
<section className="section dark"><div className="container split"><Reveal className="sticky-visual"><Image src="/images/murillo-cirurgia.webp" fill sizes="(max-width:900px) 92vw, 46vw" alt="Cirurgia ginecológica minimamente invasiva"/></Reveal><div className="split-copy"><Reveal><span className="kicker light">Cirurgia ginecológica</span><h2>Menos invasão. Mais precisão no caminho do tratamento.</h2><p>Atuação em laparoscopia, histeroscopia e outras vias cirúrgicas, sempre definidas conforme diagnóstico, anatomia, objetivos e segurança de cada paciente.</p></Reveal><div className="mini-list"><Reveal delay={.05}><div><ScanLine/><span><b>Histeroscopia</b>Diagnóstico e tratamento intracavitário.</span></div></Reveal><Reveal delay={.1}><div><Syringe/><span><b>Laparoscopia</b>Acesso por pequenas incisões quando indicado.</span></div></Reveal><Reveal delay={.15}><div><Stethoscope/><span><b>Planejamento individual</b>A técnica é escolhida caso a caso.</span></div></Reveal></div><Link className="text-link" href="/tratamentos">Explorar procedimentos <ArrowUpRight/></Link></div></div></section>
<section className="section soft"><div className="container"><Reveal><div className="section-head compact"><span className="kicker">Condições tratadas</span><h2>Investigação cuidadosa para que o tratamento comece pela causa.</h2></div></Reveal><div className="condition-cloud">{conditions.map((x,i)=><Reveal delay={i*.035} key={x}><span>{x}</span></Reveal>)}</div></div></section>
<section className="section"><div className="container about-grid"><Reveal><div className="portrait-wrap"><Image src="/images/murillo-profile.webp" fill sizes="(max-width:900px) 92vw, 38vw" alt="Dr. Murillo José Hryniewicz Santos"/></div></Reveal><Reveal delay={.1}><div className="about-copy"><span className="kicker">Sobre o médico</span><h2>Da adolescência à pós-menopausa, um cuidado pensado para a mulher por inteiro.</h2><p>Dr. Murillo José H. Santos atua há 7 anos como médico e há 4 anos especificamente no cuidado à saúde da mulher. É especialista em Ginecologia e Obstetrícia e em Endoscopia Ginecológica.</p><ul><li>Medicina pelo Centro Universitário Uningá</li><li>Ginecologia e Obstetrícia pelo Unicelular – Maringá/PR</li><li>Endoscopia Ginecológica pela UNESP – Botucatu/SP</li></ul><Link className="btn ghost" href="/sobre">Conhecer trajetória</Link></div></Reveal></div></section>
<section className="section clinic"><div className="container"><Reveal><div className="section-head"><span className="kicker">Dahlia Medical Clinic</span><h2>Um espaço contemporâneo para um atendimento tranquilo.</h2><p>{site.address} · {site.hours}</p></div></Reveal><div className="clinic-grid"><Reveal><Image src="/images/clinica-1.webp" fill sizes="(max-width:900px) 92vw, 40vw" alt="Sala de espera da Dahlia Medical Clinic"/></Reveal><Reveal delay={.08}><Image src="/images/clinica-2.webp" fill sizes="(max-width:900px) 92vw, 40vw" alt="Recepção da Dahlia Medical Clinic"/></Reveal><Reveal delay={.16}><Image src="/images/clinica-3.webp" fill sizes="(max-width:900px) 92vw, 40vw" alt="Fachada da Dahlia Medical Clinic em Maringá"/></Reveal></div><a className="btn primary" href={site.maps} target="_blank">Ver no mapa <ArrowUpRight size={18}/></a></div></section>
<section className="section"><div className="container"><div className="section-head row"><div><span className="kicker">Conteúdo médico</span><h2>Artigos para entender melhor sua saúde.</h2></div><Link className="text-link" href="/artigos">Todos os artigos <ArrowUpRight/></Link></div>{articles.length? <div className="articles-grid">{articles.map(a=><Link href={`/artigos/${a.slug}`} className="article-card" key={a.slug}><span>{a.category}</span><h3>{a.title}</h3><p>{a.excerpt}</p><small>{new Date(a.publishedAt).toLocaleDateString('pt-BR')}</small></Link>)}</div>:<div className="empty-articles"><p>Novos conteúdos serão publicados em breve.</p></div>}</div></section>
<section className="cta"><div className="container cta-inner"><Reveal><span className="kicker light">Agendamento</span><h2>Seu cuidado pode começar com uma conversa.</h2><p>Atendimento presencial em Maringá às sextas-feiras, das 8h às 12h.</p><a className="btn white" href={whatsapp()} target="_blank">Falar no WhatsApp <ArrowUpRight size={18}/></a></Reveal></div></section>
</>}
